### ISSUE TITLE
more diagnostics of whether a survey spectrum is well modeled?

### ISSUE THREAD

**Issue by HWRix** [mkness/TheCannon#22]
ISSUE  -- thoughts on diagnostics of whether the best-fit model spectrum step should make us believe that all is well with the label transfer on a given object: as I understand it, the current diagnostic is a chi-squared, which identifies some outliers but not all, eg not the rapid rotators. But there are other diagnostics that could be run on the residual spectrum, i.e.  the spectrum that is the difference between the survey spectrum and its best-fit model spectrum in the test step: I could imagine that either the Fourier transform or the auto-correlation or some other  pixel-statistic could diagnose different kinds of problems. This is probably for paper II.

**Comment by mkness** [comment]
we return a chi2 for each star but I have not mentioned this in the paper.

**Comment by davidwhogg** [comment]
It might be good to make a quick plot of our differences with ASCAP (or distances from the isochrone) vs chi^2

**Comment by mkness** [comment]
very old versions of these plots live here: http://www.mso.anu.edu.au/~mkness/
I will generate new versions.
