### ISSUE TITLE
odd paragraph in introduction

### ISSUE THREAD

**Issue by davidwhogg** [mkness/TheCannon#26]
"Our aim is distinct from simply determining parameters or finding the best fit spectra similarly to minimisation techniques.  Our aim is to implement a procedure that makes it possible to understand and characterise the spectra as a function of the labels which describe it."

Not sure what this paragraph is really about or whether it hangs together.  It needs some love from HWR, perhaps?

**Comment by mkness** [comment]
Ok I am happy to omit this and will comment it out now as it is beyond the scope of the paper. I was trying to emphasise that what we are doing goes beyond another pipeline for stellar params. and returning a best fit value, which is the way I think this domain is being thought about at present: best fit -> answer -> science; with what we are doing there are broader applications.
