### ISSUE TITLE
Section titles

### ISSUE THREAD

**Issue by HWRix** [mkness/TheCannon#29]
DWH expressed puzzlement on Section titles 2.3., 2.3.1. and 5: "why have separate explicit headings pointing to the APOGEE data? Isn't the whole paper about the APOGEE?"

HWR's view : this paper is NOT foremost about APOGEE spectra or APOGEE post-processing; 
  this is foremost a (generic) methods paper, where we use APOGEE data to illustrate the power.
 There are, by necessity, aspects that are generic (Sections 3 & 4 are almost entirely generic).
 My proposal was to not get painted into that corner, by separating APOGEE out.
 Admittedly, in the data section that is tricky. But even there, there are generic features
 (restframe, identical LSF and pixel coverage, consistent continuum normalization,
   iterative identification of good continuum pixels etc..) that are generic to any spectral survey..

I am perfectly happy to change wording, or even go back to "it's all about Apogee", but wanted to make the pitch again one more time...

**Comment by davidwhogg** [comment]
No I agree completely -- APOGEE is just an example -- but the subsection titles are very vague -- each one just re-expresses the point of the section.  They need to be either more specific or removed.  I want MORE specificity not less.
