### ISSUE TITLE
Choices for FeH and Hyades stars in Section sec:ApogeeRefLabels

### ISSUE THREAD

**Issue by HWRix** [mkness/TheCannon#30]
For ASPCAP corrected labels for the reference objects, this Section is confusing:
do you just take the pipeline values for FeH, or do you force them to be equal.
Or do you take the ASPCAP FeH's in some clusters, and "adopting" a cluster-wide FeH in others?

When talking about the "dwarfs", please make sure the reader knows all fudges and corrections 
only apply to the specific case of the Hyades....

@mkness : pls. clean up

**Comment by mkness** [comment]
There are no pipeline corrected (so no ASPCAP-corrected) values for the dwarf stars, so for this cluster, The Pleiades, (and this cluster only), I take the literature value of this cluster for all stars, a single value. I will make this clearer in the text.

**Comment by HWRix** [comment]
OK. Please make this clearer in next iteration

**Comment by mkn** [comment]
I am wondering why on earh I keep getting messages from here as I have no idea what the discussion is all about. My login is "mkn" and the damn Github system figures out that I need them so there MUST be a bug in the system.

**Comment by davidwhogg** [comment]
I think it is because @HWRix cited @mkn instead of @mkness .  Sorry about this; I think if we edit you out of the original comment, your notifications will stop.

**Comment by davidwhogg** [comment]
fixing comments now
