### ISSUE TITLE
continuum explanation

### ISSUE THREAD

**Issue by davidwhogg** [mkness/TheCannon#37]
I feel like the explanation of how we compute the continuum (spline through a set of pre-defined wavelengths) should be separated from the discussion of *how* we found those wavelengths.  The former should be in the discussion of the APOGEE data and the latter should appear after we have described the method and implementation.  Section cross-references could connect these two parts.

**Comment by mkness** [comment]
Agreed that the way this read made no sense - we introduced things talking about the normalisation that we had not described (e.g. the apstar files etc). I have moved this to other sections perhaps not quite as described above but I think it still works.
