### ISSUE TITLE
some reshuffling of discussion Section?

### ISSUE THREAD

**Issue by HWRix** [mkness/TheCannon#40]
again in the spirit of separating the generic from the Apogeean, while still
using Apogee as an example for each point.

plan is to preserve much of David's discussion, but do some reshuffle; minmap below
![discussion](https://cloud.githubusercontent.com/assets/5234830/5749053/52e7c198-9c02-11e4-9d55-532b6bdfb4da.png)

**Comment by davidwhogg** [comment]
fine with me!
