### ISSUE TITLE
`step()` requires `where` argument

### ISSUE THREAD

**Issue by davidwhogg** [mkness/TheCannon#44]
Everywhere we have `step()` we need the kwarg `where = "mid"`.  CRITICAL BUG

**Comment by davidwhogg** [comment]
This might also affect code written by @annayqho

**Comment by mkness** [comment]
davidwhogg can you explain further I am not understanding this issue.

**Comment by mkness** [comment]
Ok I think you are talking about where we generate the plots - yes, with step(). will fix in code, remake plots and close whence done.

**Comment by davidwhogg** [comment]
I think you mean "when"!  But yeah, `plt.step()` is a very, very bad function!

**Comment by annayqho** [comment]
My code doesn't use that function, but thanks for the heads-up!

**Comment by davidwhogg** [comment]
it should -- imho we should always plot spectra using `plt.step(lambda, flux, where="mid")`

**Comment by annayqho** [comment]
ah, okay. I'll add that as an issue, then!
